name: Data Preprocessing Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

# JURUS PAMUNGKAS: Paksa berikan izin tulis ke GitHub Actions
permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Run Automate Script
        run: |
          python automate_Harianja.py

      - name: Check Created Files (Debugging)
        run: |
          echo "Mengecek isi folder data_preprocessing:"
          ls -la data_preprocessing/

      - name: Commit and Push Cleaned Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data_preprocessing/hour_cleaned.csv || git add .
          git status
          git commit -m "auto: update cleaned dataset" || echo "Tidak ada perubahan data"
          git push origin HEAD:main